### ISSUE TITLE
複数階層のアイテム・フォルダの移動に時間がかかる

### ISSUE THREAD

**Issue by kazu0617** [KisaragiEffective/neosvr-inventory-management#23]
三階層下に移動させようとすると無限に読み込み状態になる

恐らく第一階層の時点で適切なフォルダを選択するかフォルダのRecordIdの指定が必要。
三階層もあるとPublicFolderの下も確認しようとし、フォルダが大量にある場合はそれぞれ見ようとして処理が終わらない

5-10分/1アイテムかかるがそれだけ待てば終わる模様。
ログを確認するとパブリックフォルダの階層（link先も？）まで見に行っている。

**Comment by KisaragiEffective** [comment]
メモ: https://neos-api.polylogix.studio/#tag/Records/operation/getRecord を使う

**Comment by KisaragiEffective** [comment]
fixed by #35
